[package]
name = "llvm-rust"
version = "0.1.0"
authors = ["hoangpq <pquochoang2007@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.3"
llvm-sys = "110"
lazy_static = "1.4.0"
